services:
  node:
    build:
      context: ./node
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s ./docker-entrypoint.sh node ./index.js
    volumes:
      - ./node:/app
    networks:
      - desafio-network
    container_name: node

  nginx:
    build:
      context: ./nginx
    networks:
      - desafio-network
    container_name: nginx
    ports:
      - 8080:80

  mysql:
    image: mysql
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=desafio
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - desafio-network

networks:
  desafio-network:
    driver: bridge
